umeng crash
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.loyo.oa.v2/com.loyo.oa.v2.activityui.customer.MyContactMailList}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
	at android.app.ActivityThread.access$900(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
	at com.loyo.oa.v2.tool.ContactInfoUtil.getMyCallContactInfo(ContactInfoUtil.java:40)
	at com.loyo.oa.v2.activityui.customer.MyContactMailList.initUI(MyContactMailList.java:114)
	at com.loyo.oa.v2.activityui.customer.MyContactMailList.onCreate(MyContactMailList.java:57)
	at android.app.Activity.performCreate(Activity.java:6367)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
	... 9 more
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
	at com.loyo.oa.v2.tool.ContactInfoUtil.getMyCallContactInfo(ContactInfoUtil.java:40)
	at com.loyo.oa.v2.activityui.customer.MyContactMailList.initUI(MyContactMailList.java:114)
	at com.loyo.oa.v2.activityui.customer.MyContactMailList.onCreate(MyContactMailList.java:57)
	at android.app.Activity.performCreate(Activity.java:6367)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
	at android.app.ActivityThread.access$900(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)