umeng crash
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.loyo.oa.v2/com.loyo.oa.v2.activityui.wfinstance.WfInEditActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2426)
	at android.app.ActivityThread.access$900(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5318)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.loyo.oa.v2.customview.WfinEditViewGroup.bindView(WfinEditViewGroup.java:159)
	at com.loyo.oa.v2.activityui.wfinstance.presenter.impl.WfinEditPresenterImpl.editTypeData(WfinEditPresenterImpl.java:155)
	at com.loyo.oa.v2.activityui.wfinstance.presenter.impl.WfinEditPresenterImpl.setStartendTime(WfinEditPresenterImpl.java:130)
	at com.loyo.oa.v2.activityui.wfinstance.WfInEditActivity.initView(WfInEditActivity.java:132)
	at com.loyo.oa.v2.activityui.wfinstance.WfInEditActivity.onCreate(WfInEditActivity.java:94)
	at android.app.Activity.performCreate(Activity.java:6024)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
	... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at com.loyo.oa.v2.customview.WfinEditViewGroup.bindView(WfinEditViewGroup.java:159)
	at com.loyo.oa.v2.activityui.wfinstance.presenter.impl.WfinEditPresenterImpl.editTypeData(WfinEditPresenterImpl.java:155)
	at com.loyo.oa.v2.activityui.wfinstance.presenter.impl.WfinEditPresenterImpl.setStartendTime(WfinEditPresenterImpl.java:130)
	at com.loyo.oa.v2.activityui.wfinstance.WfInEditActivity.initView(WfInEditActivity.java:132)
	at com.loyo.oa.v2.activityui.wfinstance.WfInEditActivity.onCreate(WfInEditActivity.java:94)
	at android.app.Activity.performCreate(Activity.java:6024)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2426)
	at android.app.ActivityThread.access$900(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5318)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)